# usage... 
# ansible-playbook -i inventories/... compliance.yaml -e devsec_hardening_target="group/host"
# or... define a group in the inventory...
# ansible-playbook -i inventories/... compliance.yaml

- hosts: "{{ devsec_hardening_target | default('devsec_hardening_target') }}"
  become: yes
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
  vars: 
    ansible_role_name: os_hardening
